language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
services:
  - mongodb
before_script:
  - mysql -e 'create database quicksearch_test;'
env:
  - DATABASE_URL="sqlite3::memory"
  - DATABASE_URL="mysql2://root@localhost/quicksearch_test"